use serde::Serialize;

/// The full companion event catalog (architecture.md AMENDMENT §A2).
/// `as_str()` is what gets looked up against `xp_rules.event_type` and
/// logged verbatim into `companion_event_log`, so the string form here is
/// the source of truth other tables reference — keep it stable.
///
/// Note: `xp_rules` still holds a `FlashcardMilestoneReached` row (migration
/// 0003, which is immutable). It is unused — there is no flashcard feature —
/// and harmless; add the variant back alongside the feature that emits it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CompanionEventType {
    TaskCompleted,
    MajorTaskCompleted,
    ExamCompleted,
    HighExamScore,
    PerfectExamScore,
    WeeklyGoalCompleted,
    StudySessionCompleted,
    PomodoroCompleted,
    StudyStreakReached,
    GoalMissed,
    StreakBroken,
    // Self-generated by the engine, not emitted by domain modules directly.
    LevelUp,
    EvolutionUnlocked,
}

impl CompanionEventType {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::TaskCompleted => "TaskCompleted",
            Self::MajorTaskCompleted => "MajorTaskCompleted",
            Self::ExamCompleted => "ExamCompleted",
            Self::HighExamScore => "HighExamScore",
            Self::PerfectExamScore => "PerfectExamScore",
            Self::WeeklyGoalCompleted => "WeeklyGoalCompleted",
            Self::StudySessionCompleted => "StudySessionCompleted",
            Self::PomodoroCompleted => "PomodoroCompleted",
            Self::StudyStreakReached => "StudyStreakReached",
            Self::GoalMissed => "GoalMissed",
            Self::StreakBroken => "StreakBroken",
            Self::LevelUp => "LevelUp",
            Self::EvolutionUnlocked => "EvolutionUnlocked",
        }
    }
}

/// A companion event as emitted by a domain module. `payload` is free-form
/// JSON (e.g. `{"taskId": 12}`) logged for audit/debugging — the engine's
/// XP/happiness/mood logic never inspects it in v1, only `event_type`.
#[derive(Debug, Clone, Serialize)]
pub struct CompanionEvent {
    pub event_type: &'static str,
    pub payload: serde_json::Value,
}

impl CompanionEvent {
    pub fn new(event_type: CompanionEventType, payload: serde_json::Value) -> Self {
        Self {
            event_type: event_type.as_str(),
            payload,
        }
    }
}
